/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 ./public/models/cloud2.gltf -t
*/
import React from "react";
import { useGLTF } from "@react-three/drei";
import { fadeOnBeforeCompile } from "@/utils/fadeMaterials";
import * as THREE from "three";

export function Cloud2({ opacity = 1, ...props }) {
  const { nodes, materials } = useGLTF("/models/cloud2.gltf");

  return (
    <group {...props} dispose={null}>
      <mesh castShadow={false} geometry={nodes.cloud2.geometry}>
        <meshStandardMaterial
          side={THREE.FrontSide}
          envMapIntensity={2}
          onBeforeCompile={fadeOnBeforeCompile}
          transparent
          color={"white"}
          roughness={0.8}
          opacity={opacity}
          metalness={0}
        />
      </mesh>
    </group>
  );
}

useGLTF.preload("/models/cloud2.gltf");
