/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 paperPlane.glb -t
*/

import * as THREE from "three";
import React from "react";
import { useGLTF } from "@react-three/drei";
export function Plane(props) {
  const { nodes, materials } = useGLTF("/models/plane.gltf");
  materials.White.side = THREE.DoubleSide;
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plane.geometry} material={materials.White} />
    </group>
  );
}

useGLTF.preload("/models/plane.gltf");
