import Footer from "@/components/Footer";
import "../styles/globals.css";
import type { Metadata } from "next";
import { DM_Sans, Montserrat } from "next/font/google";
import NavbarBasicPreview from "@/components/navbar";
import Head from "next/head";
import Header from "@/components/Header copy";

const mont = Montserrat({ subsets: ["latin"], display: "swap" });
// const inter = DM_Sans({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="">
      <Head>
        {/* <!-- HTML Meta Tags --> */}
        <title key="title">Agency</title>
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <meta name="description" content="Agency description" />
      </Head>
      <body
        className={`bg-white ${mont.className} mx-auto overflow-hidden w-screen min-h-screen h-full`}
      >
        {/* <NavbarBasicPreview /> */}
        <Header />
        {children}
      </body>
    </html>
  );
}
